### ISSUE TITLE
Suggestion: Add support for std::pair<T1, T2>

### ISSUE THREAD

**Issue by myermo** [jermp/essentials#5]
The title says it all :D

We have support for vectors and arrays, this structure should not be a problem for the library itself.

When trying to serialize a std::pair, we got this error:

`error: 'struct std::pair<int, int>' has no member named 'visit'
  362 |             val.visit(*this);`

Thanks in advance.

**Comment by jermp** [comment]
Hello @myermo,
I do not think we should add support for `std::pair`. The "correct" way of achieving what you want to do is to define a class `my_pair` which implements the `visit` method, and then have a `std::vector<my_pair<T1,T2>>`. In the end, `std::pair` is nothing special: it's just a class with two fields and I claim we should never use it but prefer meaningfully-named fields (not just "first" and "second").

**Comment by myermo** [comment]
Yep, that was exactly my workaround. I wanted to know the reasoning behind not supporting std::pair. Thanks for the quick answer!

**Comment by jermp** [comment]
You're welcome. To me, that's not a workaround -- it's exactly how it should be. In synthesis, `std::pair` and `std::tuple` suck! :)
