### ISSUE TITLE
Including multiple libraries that all ship with the essentials library breaks compilation

### ISSUE THREAD

**Issue by ByteHamster** [jermp/essentials#6]
I have a project with two libraries. Both libraries depend on the essentials library. When compiling, I get a problem because the contents in the header file are defined twice. Note that `#pragma once` does not help in this case because there are two versions of the essentials file.

I can imagine two possible solutions:
- Use cmake to create an `essentials` target that can check whether another copy of the library is already included in the project. This requires cmake and include path changes in all users of the library.
- Create/check a custom `define` in this library. This just requires git submodule updates in all users of the library.

I think the first solution is more elegant, but requires working a bit with cmake (most importantly, pthash can then no longer reference a relative file path to the library but needs to rely on the include directory setup through cmake).

**Comment by jermp** [comment]
Hi Hans-Peter,
oh I never tried that. Thanks for reporting (although it is not a problem of essentials). But I wonder what are these two libraries of mine that both ship with essentials?

Currently, PTHash is the only library that uses essentials as a submodule.
(SSHash depends on PTHash, hence it does not have to include essentials again. And similarly, Fulgor depends on SSHash, so it does not include essentials explicitly.)

Solution 1 seems very reasonable but I do not currently know how to do it with cmake. I'll try some hack!

**Comment by ByteHamster** [comment]
The other library is actually our GPU implementation :) I can take a stab at it if you are interested

**Comment by jermp** [comment]
Ahhh right. So we have the PTHash and the GPU version, both imported to another project for benchmarking?

The problem seems of general interest, so a solution should be found, yes. Let me know if you come up with a clean way of doing it. I'll replicate the problem myself.
